alias ll='ls -al'
alias drush='sudo -u www-data drush'
alias svn='sudo -u www-data svn'
alias git='sudo -u www-data git'
alias wget='sudo -u www-data wget'
alias ssh='sudo -u www-data ssh'

export NVM_DIR=/usr/local/nvm
source /opt/nvm/nvm.sh